### ISSUE TITLE
Error in Exomedepth CallCNVs function 

### ISSUE THREAD

**Issue by Shrutik08** [vplagnol/ExomeDepth#26]
Hi, 

I was running Exomedepth package for cnv detection from germline CNV's, its running fine till RData file creation but it is throwing an error when its running CallCNVs function, the error is:

Now computing the likelihood for the different copy number states
Error in CallCNVs(x = all.exons, transition.probability = 10^-4, chromosome = refcounts.dafr$space,  :
  Chromosome, start and end vector must have the same lengths.

Can you please explain what this error means? I am not able to debug this error, this will be very helpful.

**Comment by vplagnol** [comment]
mmmm... Not sure. 
Can you please run a `head(refcounts.dafr)` and tell me what you see?
I wonder if `space` should now be `seqnames` or something like this.

**Comment by Shrutik08** [comment]
Hi Vincent,

Yes I checked, space should be seqnames actually I aws using the
latest exomeDepth version and the attributes/header details that I am using
are of old version, so its throwing an error.Thanks alot for your help.
Thanks for your quick response.

The issue is fixed now.

Thanks & Regards
Shruti Kapil
