### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by CCgenetics15** [vplagnol/ExomeDepth#4]
Hi,
I'm trying to use ExomeDepth but I have the following error message:

my.counts <- getBamCounts(bed.frame = exons.hg19,bam.files= sample1.bam, include.chr=TRUE)
Parse 1 BAM files
[1] "sample1.bam"
Now parsing sample1.bam
[bam_header_read] EOF marker is absent. The input is probably truncated.
Parsing chromosome chr1
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_index_load] fail to load BAM index.
Error in value[[3L]](cond) : 
  failed to open BamFile: failed to load BAM index
  file:sample1.bam
Inoltre: Warning messages:
1: 'isNotPrimaryRead' is deprecated.
Use 'isSecondaryAlignment' instead.
See help("Deprecated") 
2: 'isNotPrimaryRead' is deprecated.
Use 'isSecondaryAlignment' instead.
See help("Deprecated") 

> help("Deprecated")
> Can you help me?
> Thanks

**Comment by vplagnol** [comment]
Can you try exomeDepth version 1.1.6 please, just pushed to CRAN last night?
But besides that it looks like there is something wrong with your BAM file,
based on the error message.

On Thu, Sep 3, 2015 at 8:22 AM, CCgenetics15 <notifications@github.com>
wrote:

> Hi,
> I'm trying to use ExomeDepth but I have the following error message:
>
> my.counts <- getBamCounts(bed.frame = exons.hg19,bam.files= sample1.bam,
> include.chr=TRUE)
> Parse 1 BAM files
> [1] "sample1.bam"
> Now parsing sample1.bam
> [bam_header_read] EOF marker is absent. The input is probably truncated.
> Parsing chromosome chr1
> [bam_header_read] EOF marker is absent. The input is probably truncated.
> [bam_index_load] fail to load BAM index.
> Error in value[3L] <http://cond> :
> failed to open BamFile: failed to load BAM index
> file:sample1.bam
> Inoltre: Warning messages:
> 1: 'isNotPrimaryRead' is deprecated.
> Use 'isSecondaryAlignment' instead.
> See help("Deprecated")
> 2: 'isNotPrimaryRead' is deprecated.
> Use 'isSecondaryAlignment' instead.
> See help("Deprecated")
>
> help("Deprecated")
> Can you help me?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vplagnol/ExomeDepth/issues/4>.
>



-- 
Vincent Plagnol
University College London Genetics Institute
Darwin building, office 210
Gower Street, London, WC1E 6BT
Cell: +44-(0)7946-546923
Office: +44-(0) 2031-084002
Website: http://www.ucl.ac.uk/ugi/research/vincentplagnol
Lab blog: http://plagnol-lab.blogspot.co.uk/

**Comment by CCgenetics15** [comment]
Hi Vincent, I tried the last version of ExomeDepth. I had the same error. I used another bam file and the program worked without problems. So now I don't know what goes wrong with the first bam file. Do you have any suggestion?
Thanks for your help

**Comment by vplagnol** [comment]
This is a very old issue, I presume not relevant anymore and I will close.
