### ISSUE TITLE
  Chromosome, start and end vector must have the same lengths

### ISSUE THREAD

**Issue by zgtman** [vplagnol/ExomeDepth#41]
Dear creators of ExomeDepth,

I am facing very curious Error form my Agilent WES BAM files. 

Can anybody tell me why I have ths kind of error?

```
Error in CallCNVs(x = all_exons, transition.probability = 10^-4, chromosome = countdf$chromosome,  : 
  Chromosome, start and end vector must have the same lengths.
Calls: CallCNVs -> CallCNVs
In addition: Warning messages:
1: In aod::betabin(data = data.for.fit, formula = as.formula(formula),  :
  The data set contains at least one line with weight = 0.

2: In model.matrix.default(mt, mfb, contrasts) :
  non-list contrasts argument ignored
3: In aod::betabin(data = data.for.fit, formula = as.formula(formula),  :
  The data set contains at least one line with weight = 0.

4: In model.matrix.default(mt, mfb, contrasts) :
  non-list contrasts argument ignored
5: In aod::betabin(data = data.for.fit, formula = as.formula(formula),  :
  The data set contains at least one line with weight = 0.

6: In model.matrix.default(mt, mfb, contrasts) :
  non-list contrasts argument ignored
7: In model.matrix.default(mt, mfb, contrasts) :
  non-list contrasts argument ignored
8: In model.matrix.default(mt, mfb, contrasts) :
  non-list contrasts argument ignored
9: In aod::betabin(data = data.for.fit, formula = as.formula(formula),  :
  The data set contains at least one line with weight = 0.

10: In model.matrix.default(mt, mfb, contrasts) :
  non-list contrasts argument ignored
Execution halted
```
Thank you so much for any help,

Paul.

**Comment by master-noddy** [comment]
I also got this same error.
Convert the exon file into a tab-separated file and then try running the script

**Comment by lmanchon** [comment]
this is what i have done and nothing change for me:

Error in CallCNVs(x = all.exons, transition.probability = trans_prob,  : 
  Chromosome, start and end vector must have the same lengths.
De plus : Warning messages:
1: In aod::betabin(data = data.for.fit, formula = as.formula(formula),  :
  The data set contains at least one line with weight = 0.
bla bla bla

short extract of my bed:
chr	Start	end	Gene
chr1	11868	12227	DDX11L1
chr1	12612	12721	DDX11L1
chr1	13220	14409	DDX11L1
chr1	14403	14501	WASH7P
chr1	15004	15038	WASH7P
chr1	15795	15947	WASH7P
chr1	16606	16765	WASH7P
chr1	16857	17055	WASH7P
chr1	17232	17368	WASH7P
chr1	17368	17436	MIR6859-1
chr1	17605	17742	WASH7P
chr1	17914	18061	WASH7P
chr1	18267	18366	WASH7P
chr1	24737	24891	WASH7P
chr1	29533	29570	WASH7P
chr1	29553	30039	MIR1302-2HG
chr1	30365	30503	MIR1302-2
chr1	30563	30667	MIR1302-2HG
chr1	30975	31097	MIR1302-2HG
chr1	34553	35174	FAM138A
chr1	35276	35481	FAM138A
chr1	35720	36081	FAM138A

**Comment by uhany2** [comment]
I am getting the same error, can anyone please help?

**Comment by mbujnis** [comment]
I have the same error. Was this ever solved?

**Comment by Jolleboll** [comment]
Hello. The error message is incomplete. It should say:

Chromosome, **name**, start and end vectors must have the same lengths.

My problem was that my "names" vector was called "exon", so copy-pasting from the vignette meant my names-vector had length zero, which indeed is not the same as the other three vectors. But, the error message is incomplete, as I said.

**Comment by vplagnol** [comment]
Thanks- it looks like I need to update the error message! Let me try to do that now.

**Comment by vplagnol** [comment]
And version 1.1.17 should have an updated error message. You can try from github. It may not quite warrant a CRAN update, but I'll try to bundle that with whatever additional fixes before I update on the repo.

Thanks again!
