### ISSUE TITLE
ExomeDepth-vignette.pdf mess up

### ISSUE THREAD

**Issue by boboppie** [vplagnol/ExomeDepth#5]
Dear Vincent,

Thanks for v1.1.6 update. I notice the vignette pdf is messed up in section 9. The content in p10 should go under section 9 in p9, right?

Best wishes,
Fengyuan

**Comment by vplagnol** [comment]
Many thanks for pointing it out Fenguyan and sorry for taking forever to reply.
I think I have now fixed the issue with a \clearpage at the right location and I will push the update to CRAN later today.
