### ISSUE TITLE
 install  Error

### ISSUE THREAD

**Issue by user-tq** [vplagnol/ExomeDepth#51]
i try to install DEcON,but it cant install ExomeDepth
```
Retrieving 'https://cran.ma.imperial.ac.uk/src/contrib/Archive/ExomeDepth/ExomeDepth_1.1.15.tar.gz' ...
Warning: failed to find source for 'ExomeDepth 1.1.15' in package repositories
Warning: failed to retrieve 'https://cran.ma.imperial.ac.uk/src/contrib/Archive/ExomeDepth/ExomeDepth_1.1.15.tar.gz' [error code 22]
Error: failed to retrieve package 'ExomeDepth@1.1.15'
In addition: There were 11 warnings (use warnings() to see them)
Traceback (most recent calls last):
```
try to rearch ExomeDepth on cran ,I get that
![image](https://user-images.githubusercontent.com/72878144/195807696-072894c8-50e1-4659-8e52-d91f479e87e0.png)
https://cran.r-project.org/web/packages/ExomeDepth/index.html

**Comment by vplagnol** [comment]
Thanks and yes I am aware.

CRAN is objecting to the fact that I incldued some GSL library code (all
open source) into my package instead of having it as a dependency.
I find it absolutely silly- GSL is large and it was easier for me to copy
chunks of code, with all the proper attributions in the code base.
I'll try to sort it out with CRAN, so apologies about this.

**Comment by vplagnol** [comment]
OK package back on CRAN now.

**Comment by abernar-85** [comment]
I am still having same issue when installing DECoN:

`Retrieving` 'https://cran.ma.imperial.ac.uk/src/contrib/Archive/ExomeDepth/ExomeDepth_1.1.15.tar.gz' ...
Warning: failed to find source for 'ExomeDepth 1.1.15' in package repositories
Warning: failed to retrieve 'https://cran.ma.imperial.ac.uk/src/contrib/Archive/ExomeDepth/ExomeDepth_1.1.15.tar.gz' [error code 22]
Error: failed to retrieve package 'ExomeDepth@1.1.15'
In addition: There were 11 warnings (use warnings() to see them)`

**Comment by vplagnol** [comment]
Yes the version of ExomeDepth on CRAN is now 1.1.16. Someone should tell DECon to look for a more recent ExomeDepth, I suppose something is hardcoded in the DECon code?
