### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pd3** [vplagnol/ExomeDepth#57]
I'd like to try ExomeDepth because it came out favourable in comparison of other CNV callers https://www.nature.com/articles/s41598-021-93878-2

I installed the package using 
```
if (!require("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("ExomeDepth")
```

and now I am trying to understand how to run it. Is there a document that describes best practices, or any documentation showing how to actually run it?

**Comment by vplagnol** [comment]
I am hoping that the vignette tells you everything you need to know? You should be able to access it from CRAN or the installed package itself.

**Comment by pd3** [comment]
Uh, this seems to assume a background knowledge which I don't have. I am not familiar with .Rnw files and would not guess a file named `vignette.Rnw` contains the documentation!

Perhaps creating a txt / pdf / html file in a subdirectory labeled 'doc' or 'documentation' would help users like me :)

Thank you for the prompt response.

**Comment by vplagnol** [comment]
It's the pdf version of the vignette that you want. See this link:
https://cran.r-project.org/web/packages/ExomeDepth/vignettes/ExomeDepth-vignette.pdf

**Comment by vplagnol** [comment]
And to be 100% clear because you may not have worked with these features before, but the magic of R is to create the pdf version of the vignette directly from the markdown Rnw file, so that you can see exactly what is going on.
